[build]
  base    = "Project Folder"  # <--- ADD THIS LINE
  command = "npm run build"
  publish = "Project Folder/dist" # <--- IMPORTANT: Update the publish path

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200